### ISSUE TITLE
$150 - Define Object Model

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#1]
Create all of the models as specified in the Swagger file. There is a placeholder model to get you started in /models/Blog.js. Make sure you use embedded documents where appropriate like comments, etc.

One thing to note and might need to be fixed (not sure if it is important), the Swagger API uses "id" while MongoDB uses "_id".

For the Blog model, when a new record is created, it should automatically [slugify](https://www.npmjs.com/package/slugify) the title and save it as the slug.

**Comment by LOYEER** [comment]
Hi, I have sent the model definition to you via email. Please check your email, thanks.

**Comment by jeffdonthemic** [comment]
Thanks! I did see it yesterday. Will look at it shortly and enter the payment for you. THANKS!
