### ISSUE TITLE
POST /blogs/{id}/votes/downvote - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#10]
This method will down-vote a blog by current user. A blog can be up-voted by the same user for at most once. The author of blog cannot vote for the his/her blog.

**Comment by FeiZhan** [comment]
Hi I have sent an email to jeff@appirio.com to register. Could I assign this issue to me? Thanks.

**Comment by jeffdonthemic** [comment]
@lanchongyizu , same issue as the other ones. Can't get the last test to run:

Down-vote Blog test should return 403 response for down-voting blog by the author of blog:
     Error: expected 403 "Forbidden", got 200 "OK"
