### ISSUE TITLE
POST /blogs/{id}/comments - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#11]
This method will add a comment for the blog. Comments do not have any sort of hierarchy and can simply be pushed onto the array of comments.

**Comment by iit2009060** [comment]
Hey can you give the example of  adding comments to mongo db.  
I am currently doing like this , but I am getting the error

var comment = new Comment({

      author: goyarpit,
      content: 'Its a good coment',
      lastUpdateedDate: (new Date).getTime(),
      postedDate: ( new Date).getTime()


 });

 

  var b3 = new Blog({
    author: goyarpit,
    title: 'Blog Title #8',
    content: 'This is my third blog content',
    isPublished: false,
    createdDate: (new Date).getTime(),
    lastUpdatedDate: (new Date).getTime(),
    comments: [comment],
    slug: 'slug3'
  });

But this is giveing error while inserting 
 [CastError: Cast to Array failed for value "{ author: { handle: 'goyarpit', _id: 551d2493165ba4f705ba56a8 }
Can you help it.

**Comment by jeffdonthemic** [comment]
I remember this being tricky in the past. I think you *may* have to push it onto the array... something [like this](https://github.com/topcoderinc/codeyourwayin-apex/blob/master/controllers/arena.js#L159)?

**Comment by iit2009060** [comment]
How to test for the POST data in POSTMAN . I tried to put data in  form in POSTMAN , and tried to access req.body , But I am getting empty . May be its due to error in code related to bosy-parser in app.js ?

**Comment by iit2009060** [comment]
I got it .

**Comment by iit2009060** [comment]
While Using postman , req.user is not able to set . How it can be done .

**Comment by iit2009060** [comment]
I have written this code , but when I try to execute  it return 
 throw new Error('Can\'t set headers after they are sent.');


exports.addComments = function(req,res) {

	Blog.findById(req.params.blog_id,function(err,blog) {
		if (err) {
			console.log("error");
			res.send(err);
		}

	//console.log("why god  " + req.user);
	 var goyarpit = new User({
    		handle: 'goyarpit'
     });

	var comment = new Comment({
			author: goyarpit,
      		content: req.body.contentText,
      		lastUpdateedDate: (new Date).getTime(),
      		postedDate: ( new Date).getTime()
	});


 
	blog.comments.push(comment);
	
		blog.save(function(err) {
			if ( err) {
				res.send(err);
			}
			res.json(blog);
		});

});
i am not sending res twice . You have any guess for this

**Comment by iit2009060** [comment]
Please review the pull request.

**Comment by iit2009060** [comment]
@jeffdonthemic Please review the  pull request . This has been pending for a long time.

**Comment by jeffdonthemic** [comment]
@iit2009060 See the comments on the pull request with the problem for the 3 tests.

**Comment by iit2009060** [comment]
Updated the test case .please review the pull request.

**Comment by jeffdonthemic** [comment]
@iit2009060 , please correct me if I'm wrong but I've already merged a pr that fixes this issue?

**Comment by jeffdonthemic** [comment]
@iit2009060 found the test so I'm closing this issue. Thanks!!
