### ISSUE TITLE
DELETE /blogs/{blogId}/comments/{commentId} - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#13]
This method will delete a comment. It can only be done by the author of comment, or the author of blog.

**Comment by iit2009060** [comment]
Please review the existing pull request , code lies in there .

**Comment by jeffdonthemic** [comment]
@iit2009060 OK... I merged your code but I can't get 3 of your test to work. Can pull down the code from the master branch (or fork it again) and see if you can fix them. I'm not sure what is working.

**Comment by iit2009060** [comment]
Actually  what happening is I am using req.user  while executing the test case and req.user will be set only if the user tried to sign in. Is there a way in which we can set req.user in the test case .

**Comment by iit2009060** [comment]
Hi Jeff, 
Do you know how we can set the req.user object in supertest. This is the reason two of the test case failing.

**Comment by iit2009060** [comment]
I may need to call the AuthChecker everyTime when I am accessing the api to make this test work( to set the req.user object). I have seen people calling AuthChecker  for each api  example in liking comments api :(router.post('/blogs/:blogId/comments/:commentId/like', AuthChecker, blogController.likeBlogComment); But  I think it should be called only one time when user tried to sign in .There is no need to call AuthChecker everytime . Am I correct ?

**Comment by iit2009060** [comment]
Updated the test. Please review it.

**Comment by jeffdonthemic** [comment]
@iit2009060 , found the test and closing this issue. Thanks!!
