### ISSUE TITLE
POST /blogs/{blogId}/comments/{commentId}/dislike - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#15]
This method will make a comment as disliked by current user. The author of comment cannot mark the his/her comment as disliked.

**Comment by iit2009060** [comment]
The user can click the like button at most one time I guess.

**Comment by jeffdonthemic** [comment]
Correct!

**Comment by ashishgoyal21** [comment]
Will disliking a comment also involve removing the the entry likeUsers, if the user previously liked the comment, or is it possible for a user to both like and dislike the comment?

**Comment by ashishgoyal21** [comment]
Will disliking a comment also involve removing the the entry from likeUsers, if the user previously liked the comment, or is it possible for a user to both like and dislike the comment?

**Comment by jeffdonthemic** [comment]
@ashishgoyal21 I think you are correct. If they did previously like a comment, please remove them from that before adding them to the dislike. Thanks!!

**Comment by jeffdonthemic** [comment]
Closed by #32

**Comment by jeffdonthemic** [comment]
@fxish I'm trying to create payment in Jira for these issues. However, you don't show up in Jira because I don't think you've logged in yet (this creates your account).

Can you [log into Jira](https://apps.topcoder.com/bugs/secure/Dashboard.jspa) with your topcoder credentials and let me know when you've done so.
