### ISSUE TITLE
GET /blogs - $300

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#16]
This method returns the blogs that matches any number of filters.

Submission must include mocha test to ensure at least (if not more) the following are returned by:

1. handle
2. handle & slug
3. two or more tags
4. title
5. keyword
6. published date range (e.g., all blogs published from 2/1 - 4/1 with an optional author handle)

All results must support pagination and optional sortBy filters and sortType filters.

**Comment by ColorfullyMe** [comment]
@jeffdonthemic There are some problems with the Blog model!

1. Why are `createdDate` and `lastUpdatedDate` defined as `Number` type? This is wrong, mongo has the Date type for dates.
2. There is no `published date` filed in the blog schema. How to implement requirement 5 from above?
3. What is `keyword`?

**Comment by ColorfullyMe** [comment]
@jiangzhihui What is your status in the project?
1. Does not matter.
2. Wrong there is not such field maned `publishedDate`
3. Contains is fine to me...

**Comment by ColorfullyMe** [comment]
@jeffdonthemic Who should handle this issue, please decide. Me or @jiangzhihui ...

**Comment by jiangzhihui** [comment]
@ColorfullyMe I think Github is a collaboration platform. So when you ask something that i know, i'm very happy to answer ^_^. Maybe my answer is not very exact, but my goal is to get this project done well.

**Comment by jiangzhihui** [comment]
@jeffdonthemic Shall the author information be populated in the returned blogs?

**Comment by jiangzhihui** [comment]
I think  i get the answer for quesiton 1 from the response Schema :)

**Comment by jeffdonthemic** [comment]
@jiangzhihui I think a 500 for a server error and a 400 for a bad request. I think you'll need a 400 if they submit a bad string or something malformed for a search request. I'll update the swagger doc.

**Comment by jiangzhihui** [comment]
@jeffdonthemic ok, thanks!

**Comment by ColorfullyMe** [comment]
@jeffdonthemic 
1. what about my questions?
2. Do you follow the swagger file?
3. `title` is exact match, `keyword` is contains match?
4. Your requirement 6. is split into 2 parameters `publishedDateFrom` and `publishedDateTo`

**Comment by jiangzhihui** [comment]
@jeffdonthemic  
Shall only published blogs returned by this API? 
My understanding is that this API shall not return not published blogs. Please confirm it. 
Thank you!

**Comment by jeffdonthemic** [comment]
@jiangzhihui should be working on this issue since he was assigned first.  Thanks @ColorfullyMe

**Comment by ColorfullyMe** [comment]
@jeffdonthemic OK no problem. Leaving Las Vegas...

**Comment by jeffdonthemic** [comment]
@jiangzhihui Interesting... I think you are correct. By default, if isPublished if not passed, it should default false and not return unpublished blogs. It should only return unpublished blogs if isPublished is passed as true. We may have to do some tweaking in the UI that we design in the future. Thanks!!

**Comment by jiangzhihui** [comment]
@jeffdonthemic 
Question about the "totalPages" in the response json data.  I think i need a something like blogsPerPage to calculate totalPages from total blogs. But i can't find the information from the requirements or swagger doc. Or i misunderstand the requirement? 
Thank you!

**Comment by jeffdonthemic** [comment]
@jiangzhihui I think the `totalPages` has to do with the limit. So if 100 records are returned and the limit is 10 (this is the default), then the total pages would = total records / limit. Make sense?

**Comment by jiangzhihui** [comment]
Sorry, i think i misunderstood the meaning of the 'limit' filter. I thought it was a limit on the number of returned blogs. 

So, if the passed limit value is not -1, the totalPages will always be 1 and if limit is passed as -1, the totalPages=totoal/limit ?  Is that right? 
thanks!

**Comment by jeffdonthemic** [comment]
@jiangzhihui , check out [this page](https://blog.apigee.com/detail/restful_api_design_can_your_api_give_developers_just_the_information) regarding limit and offset for pagination. Offset defaults to 0.

Does this help?

/blogs?limit=100 -- returns 100 records (totalPages: total records / 100)
/blogs?limit=10&offset=2 -- returns records 21 -> 30 of resultset (totalPages: total records / 10)
/blogs?limit=-1 -- returns all records (totalPages = 1 since all records are returned)

**Comment by jiangzhihui** [comment]
@jeffdonthemic Thank you very much! The article is very helpful! 

This is my first time to know about the concept of RESTful API pagination. I learn a lot from every tc challenge! Thank you all guys from topcoder!

**Comment by jiangzhihui** [comment]
I think there are something wrong the the Blog model:
The type of tags and comments element should be a schema not mongoose model. The correct definition may be like the following:
tags:{
   type: [Tag.schema]
   ....
}
comments:{
  type: [Comments.schema]
  ...
}

**Comment by jeffdonthemic** [comment]
@jiangzhihui Feel free to change it if you think it is incorrect.

**Comment by jiangzhihui** [comment]
@jeffdonthemic 

ok. 

By the way, shall i assume the handle of user is unique?

**Comment by jeffdonthemic** [comment]
@jiangzhihui Yes... sorry. The handle will always be unique.

**Comment by jeffdonthemic** [comment]
Sorry... didn't realize you change my /tmp/load path with you mocks.
