### ISSUE TITLE
PUT /blogs/{id} - $75

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#4]
This method will update a blog record. It can only be done by the author of blog.

**Comment by jeffdonthemic** [comment]
Ensure that if the user changes the slug that it is unique per user.

**Comment by panoptimum** [comment]
Are there restrictions to the fields the user is allowed to update? E.g. is a user allowed to update numOfDownVotes?

**Comment by jeffdonthemic** [comment]
@panoptimum How about create an array of allowable updatable fields? Then you could either throw an error or possibly even remove any un-updatable properties in the object before saving.

**Comment by panoptimum** [comment]
This is what I did, I just asked about the initial configuration.

**Comment by jeffdonthemic** [comment]
Fixed by #36
