### ISSUE TITLE
GET /blogs/{id} - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#5]
This method will get a blog by ID.

**Comment by iit2009060** [comment]
How to assign this issue to myself.

**Comment by iit2009060** [comment]
I have sent a merge request . Please  instruct how to assign the issue .

**Comment by asifmohd** [comment]
@iit2009060 send a mail to jeff@appirio.com with your github username, to add you to the TopBlogger team

**Comment by iit2009060** [comment]
Already sent .

**Comment by jeffdonthemic** [comment]
@iit2009060 , github says you haven't accepted the team request yet. Waiting on you to do that before I can assign you.

**Comment by iit2009060** [comment]
Do I will get an email , or where I should go to accept the invitation.

**Comment by jeffdonthemic** [comment]
See the fourth item on [this page](https://help.github.com/articles/adding-or-inviting-members-to-a-team-in-an-organization/) for more details.

**Comment by iit2009060** [comment]
Hey Can you sent the request again . I havent received the invitation email of ypur team.

**Comment by iit2009060** [comment]
Hey Please send the instruction how i can add to the team. I have not received any invitation mail.

**Comment by jeffdonthemic** [comment]
@iit2009060 the invitation has already been sent. It goes to the email associated with your github account. You may want to check your spam folder. If you can't find it I can send it again.

![image](https://cloud.githubusercontent.com/assets/445606/6949609/3dd46faa-d86a-11e4-9441-340c49043826.png)
