### ISSUE TITLE
POST /blogs/{id}/publish - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#7]
This method will publish a unpublished blog. It can only be done by the author of blog.

**Comment by ColorfullyMe** [comment]
@jeffdonthemic Shell I assume that setting the `isPublished` flag to `true` and populating the `publishedDate` filed is what is expected here. Is there something more? Notify something for instance...

**Comment by jeffdonthemic** [comment]
I think you are correct!
