### ISSUE TITLE
POST /blogs/{id}/upvote - $25

### ISSUE THREAD

**Issue by jeffdonthemic** [topcoderinc/TopBlogger#9]
This method will up-vote a blog by current user. A blog can be up-voted by the same user for at most once. The author of blog cannot vote for the his/her blog.

**Comment by iit2009060** [comment]
How we will store which user have voted that , and they should not allowed to vote again. There will be a change in db ?

**Comment by jeffdonthemic** [comment]
@iit2009060 .... great question. Looks like that was overlooked in the model design. What if we added added to the Blog model a upVoters array of Users and a downVoters array of Users? You could then just push the User to the array if it doesn't already exist? How does that sound?

**Comment by jeffdonthemic** [comment]
@lanchongyizu I couldn't get your last test to pass. Can you pull from the master branch and see if you can see what I'm doing wrong. Here's the error:

2) Up-vote Blog test should return 403 response for up-voting blog by the author of blog:
     Error: expected 403 "Forbidden", got 200 "OK"
